Customize the top side of the portfolio
rica213/portfolio pull request #1
Opened 2022-12-01 21:45 UTC by rica213

Add a README file to the project.
Add markup to the header and the section headline.
Apply CSS rules on the header and headline for the screens with widths of fewer than 320 pixels.

2022-12-01 21:50 UTC, huseyinbiyik commented
Hi @rica213 ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that linters are not passing. Kindly fix the linters issue and ask for a new request from the dashboard.🦾

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-01 23:45 UTC, Gambit142 requested changes
Hi @rica213 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Descriptive Pull request title ✔️ 
- Descriptive pull request summary ✔️ 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-01 23:45 UTC, Gambit142 commented on index.html
> +        id="orange-triangle"><img src="img/Red-Diamond.png" alt="red-diamond-shape" id="red-diamond"></div>
- [ ] Kindly use the `background-image` property of CSS to design the header section instead of using it as an image in the markup. When designing a page for aesthetic reasons, it is semantic to use the CSS `background-image` instead of using it as an image. 👍

2022-12-01 23:45 UTC, Gambit142 commented on style.css
> +}
- [ ] Great work creating the hamburger image this way. To make your design more identical to that of the Figma template you chose, kindly make the border: `1px solid #c4c4c4` and add a declaration of` margin-bottom: 4px;`. 👍

2022-12-01 23:45 UTC, Gambit142 commented on index.html
> +    <h1 id="owner">Larissa Clarielle</h1>
- [ ] One of the major requirements for this project is to make your design look identical to that of the Figma template you chose. For the main header, kindly follow the format used in the Figma template. You can decide to use the `br` tag in the `h1` tag or you create two `span` tags in the `h1` tag. 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/205180202-311c0705-158e-4a64-824e-5b36fb446455.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/205180277-aaa95086-5732-4f95-b2f7-120fb2935599.png)

2022-12-01 23:45 UTC, Gambit142 commented on index.html
> +  </section>
- [ ] Kindly use the `a` tag for this element instead of the div tag. Using the `a` tag is semantic and, it allows you to connect to other parts of the website or external sites using the `href` attribute. 👍

2022-12-01 23:45 UTC, Gambit142 commented on style.css
> +}
For this element, kindly make the following changes:
- [ ] Remove the CSS declaration of `border: 1px solid #e45865;`. It is not used in the original template.
- [ ] Add interactions for this element (that is after you change it to an `a` tag). The interactions you will need to implement are for the hover, active and pressed states. For example:

```CSS
#collaboration:hover {
  color: blue;
  background-color: white;
}
```

Please don't use the values I used for the properties declared above. You can find the properties and values to be used when you inspect the Figma template you chose. A snapshot is attached to guide you to the section

![image](https://user-images.githubusercontent.com/77106962/205182051-d08123ce-a964-4b8f-bf36-ac628614192b.png)

Choose one of them and implement it 👍

2022-12-02 04:10 UTC, rica213 commented on README.md
> +
Thank you for your feedback. Is it mandatory to add those subsections even if they do not apply to the project?

2022-12-02 06:21 UTC, rica213 commented
@Gambit142 Thank you for the throughout feedback. I have already done the changes you recommended.

2022-12-02 07:12 UTC, Alfredbis29 requested changes
Hi @rica213 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
![](https://camo.githubusercontent.com/ea5a41c13a43074321873dea3237d149557ac13d29ccf550ac00b20bdfc39068/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Suggested changes

_Check the comments under the review._

### OPTIONAL CHANGES :brown_circle: 

- [ ] check under the review 

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-12-02 07:12 UTC, Alfredbis29 commented on index.html
> +    <p id="intro">Hello! I am a software developer! I can help you build a product, feature or website. Take a look of
- [ ] As we are imitating the Figma design, I noticed that your paragraph `font-family`  is not the same as Figma design, and I realized that you missed the image below the start button as seen on the design, please take care of this for your project to look more attractive.

Your Design 
![yours](https://user-images.githubusercontent.com/88894525/205234273-cde06193-ffb6-4ef6-9029-ac08667b866d.png)

Figma Design 
![Screenshot from 2022-12-02 08-51-32](https://user-images.githubusercontent.com/88894525/205234320-877cb1ed-a37b-47c6-858f-1bf8373be54f.png)

2022-12-02 07:12 UTC, Alfredbis29 commented on index.html
> +        id="orange-triangle"><img src="img/Red-Diamond.png" alt="red-diamond-shape" id="red-diamond"></div>
- [OPTIONAL ] Please use the background-image property of CSS to design the header section and replace it as an image in the markup, as specified in the previous review. :wink:

2022-12-02 07:52 UTC, rica213 commented
@Alfredbis29 Thank you for the review. I want to address the [OPTIONAL] recommendation. I have already used the **background-image** property. It is in the **header** branch.

2022-12-02 11:23 UTC, rica213 commented
@huseyinbiyik @Gambit142 @Alfredbis29 Hi, I encountered a problem with this PR.
I created one branch for each feature. In this case, they were "configuration", "header", and "headline".
On my first PR, my "headline" branch was the most recent, so I used it to ask for PR.
And when I received some reviews from you. I used my feature branches to fix my codes and pushed on those branches individually.
I did not open a new PR but continued to request a review of the first PR. 
However, when @Alfredbis29 mentioned that I should use "background-image" property, which I have already done but on the **header** branch, I wanted to merge all my branches into one and rename it to make more sense.
What I did was: - Merge locally on the **headline** all the branches
- Rename the branch **headline** to **custom-top-page** (local and remote)
But then, **_it closed the PR_!!!**
Now, I am asking you what should I do. I tried to reopen it but I don't know how. And all my last changes are on my new branch **custom-top-page** but I am not allowed to open a new PR.
How am I going to proceed if I want someone to review my code.

Thanks in advance,

2022-12-02 11:25 UTC, rica213 commented
@huseyinbiyik @Gambit142 @Alfredbis29 Hi, I encountered a problem with this PR.
I created one branch for each feature. In this case, they were "configuration", "header", and "headline".
On my first PR, my "headline" branch was the most recent, so I used it to ask for PR.
And when I received some reviews from you. I used my feature branches to fix my codes and pushed on those branches individually.
I did not open a new PR but continued to request a review of the first PR.
However, when @Alfredbis29 mentioned that I should use the **background-image** property, which I have already done but on the header branch, I wanted to merge all my branches into one and rename it to make more sense.
What I did was: - Merge locally on the headline all the branches

Rename the branch headline to custom-top-page (local and remote)
But then, it closed the PR!!!
Now, I am asking you what should I do. All my last changes are on my new branch custom-top-page but I am not allowed to open a new PR.
How am I going to proceed if I want someone to review my code?
Thanks in advance,

2022-12-02 12:03 UTC, Alfredbis29 commented
Hi @rica213 ,I'm sorry for the delay, I'm trying to look at your PR and what I can see your PR is still open, you can make the changes I told you, I think for the background image that was an OPTIONAL but I required you to complete your work, because you are missing that image on down the start collaboration link, for what I can suggest you, you can't merge this PR and still have some changes but you can still improving on this PR until it gets approved, thanks, if you have any other questions :wink:

2022-12-02 12:23 UTC, rica213 commented
@Alfredbis29 it is open now after I sent the message. But when I type **git branch -a** on my machine, I cannot see the **headline** branch. I cannot push on it.

2022-12-02 12:30 UTC, rica213 commented
![Screenshot from 2022-12-02 15-25-33](https://user-images.githubusercontent.com/10439283/205293070-bc1e8ea3-4de5-4618-bb91-2b03df15c580.png)

After restoring the **headline** branches, I cannot reach it from my local machine.

2022-12-02 12:31 UTC, Alfredbis29 commented
Call me on zoom I can give some help

2022-12-02 12:46 UTC, rica213 commented
@Alfredbis29 Ok.[ Join me on this call](https://microverse.zoom.us/j/99231155645?pwd=ZHhzUGtaZS9oSTdkR1hUNDhhZ2RHUT09)

2022-12-02 14:05 UTC, merged