Refactor portfolio
rica213/portfolio pull request #19
Opened 2023-07-31 14:43 UTC by rica213

Hi, 

In this PR, here is the list of things I did:
- Changed the structure of the portfolio section
- Added real projects in the portfolio section
- Updated the social media links
- Added functionality to download my resume
- Move all images in the assets/images directory
- Used font awesome for icons
- Fix inconsistent styling
- Updated skills section
- Added USP in my introduction
- Added a CTA button in the headline section
- Set navigation within project details as a future feature

Kindly review those changes. Thank you 💛

2023-07-31 19:48 UTC, shaaibu7 requested changes
Hi @rica213 

You did a great job working on your portfolio but you need to make some improvements before you move forward.

<img src="https://media3.giphy.com/media/SiGg4zSmwmbafTYwpj/giphy.gif"/>

This text has some grammatical errors. you can use Grammarly to make this correction  :point_down: 
![Screenshot from 2023-07-31 20-33-36](https://github.com/rica213/portfolio/assets/83074207/b07ef446-f59d-43ee-bc2c-a20484458c88)

The spelling below should be Capybara :point_down: 

![Screenshot from 2023-07-31 20-34-10](https://github.com/rica213/portfolio/assets/83074207/969bde79-0eba-4003-a15b-122c88991194)

Your header should be fixed at the top for both mobile and desktop versions, kindly implement that project requirement.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-31 19:48 UTC, shaaibu7 commented on index.html
>            </p>
This text has some grammatical errors, Kindly fix it. you can use Grammarly to correct this.

2023-08-01 09:15 UTC, shaaibu7 approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @rica213     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 09:22 UTC, rica213 commented
Thank you time Shaaibu ❤️ @shaaibu7

2023-08-01 09:23 UTC, merged