Design the desktop version of the portfolio
rica213/portfolio pull request #6
Opened 2022-12-15 20:06 UTC by rica213

Design the **header** section
Design the **headline** section
Design the **projects** section
Design the **about me** section
Design the **contact form** section
Design the **footer** with the **social media links**

2022-12-15 20:35 UTC, Gopxfs requested changes
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @rica213 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/l4JzhjVCQiWgeAOFa/giphy.gif">

## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!
✔️ Your design looks flawless 😉.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 20:35 UTC, Gopxfs commented on style.css
> +  }
Please make sure to adjust the gap between your `nav` links, to follow the original design 😉:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/207958765-413163c1-72f7-47df-81b9-753f41cb1963.png)  | ![image](https://user-images.githubusercontent.com/42799579/207958731-35ab3f5e-aa4e-4bc5-9ae9-ed2261770bd4.png)  |

2022-12-15 20:35 UTC, Gopxfs commented on style.css
> +  }
Great job adding the `ul` of technologies 😄! Please make sure to apply the corresponding `font-size` to the `li` elements 😉:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/207959041-6d3424a5-5bca-49a9-87f2-66202e90f0a6.png)  | ![image](https://user-images.githubusercontent.com/42799579/207959064-53c173bb-7c38-4d9f-b708-08f61b48269b.png)  | 
![image](https://user-images.githubusercontent.com/42799579/207959459-c3b57e17-baa8-4a23-922e-5b122e1b7b8f.png) | ![image](https://user-images.githubusercontent.com/42799579/207959489-c07e031c-99f8-41a1-af20-9ecab4bedbf5.png) |

Kindly make sure to adjust the padding after increasing the `font-size` 😉.


Tip: 20px = 1.25em (by default)

2022-12-15 20:35 UTC, Gopxfs commented on style.css
> +  }
Kindly notice that this background image isn't being displayed:
Figma design:
![image](https://user-images.githubusercontent.com/42799579/207960400-4b585c94-d8af-4197-9662-7d7a76b5d017.png)

Your design:
![image](https://user-images.githubusercontent.com/42799579/207960440-42abcd4a-589f-496e-9585-e07f7e2a2656.png)

Please make sure to apply all background images displayed on Figma 😉.

> Keep in mind that this project's goal is to improve your ability to follow design guidelines (imagine Microverse as a client requesting a website) 😉.

2022-12-15 20:35 UTC, Gopxfs commented on style.css
> +  }
Please make sure to apply the corresponding down padding for these sections
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/207960651-e8b9a8db-532d-47bd-8ce3-72b107bfc755.png)  | ![image](https://user-images.githubusercontent.com/42799579/207960698-f473870c-1479-43aa-a7f7-68fbcc0b5dfa.png)  | 😄:

2022-12-16 08:03 UTC, emmiiorji approved these changes
Hi @rica213,

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/207525547-7de7920a-360e-47f2-b4e7-69e3afa2af50.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow
- Requested change has been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 08:07 UTC, merged